// <auto-generated />
using Finance.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Finance.Domain.Migrations;

[DbContext(typeof(FinanceDbContext))]
[Migration("20230507005506_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

        modelBuilder.Entity("Finance.Api.Models.Bank", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Bank");
            });

        modelBuilder.Entity("Finance.Api.Models.Currency", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("ShortName")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.HasIndex("ShortName")
                    .IsUnique();

                b.ToTable("Currency");
            });

        modelBuilder.Entity("Finance.Api.Models.CurrencyConversion", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<decimal>("Amount")
                    .HasColumnType("numeric");

                b.Property<Guid?>("CurrencyId")
                    .HasColumnType("uuid");

                b.Property<Guid>("MovementId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("CurrencyId");

                b.HasIndex("MovementId");

                b.ToTable("CurrencyConversion");
            });

        modelBuilder.Entity("Finance.Api.Models.Module", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("CurrencyId")
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("CurrencyId");

                b.ToTable("Module");
            });

        modelBuilder.Entity("Finance.Api.Models.ModuleEntry", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<decimal>("Ammount")
                    .HasColumnType("numeric");

                b.Property<DateTime>("TimeStamp")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.ToTable("ModuleEntry");
            });

        modelBuilder.Entity("Finance.Api.Models.Movement", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<decimal>("Amount")
                    .HasColumnType("numeric");

                b.Property<string>("Concept1")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Concept2")
                    .HasColumnType("text");

                b.Property<Guid?>("CurrencyId")
                    .HasColumnType("uuid");

                b.Property<Guid>("ModuleId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("TimeStamp")
                    .HasColumnType("timestamp with time zone");

                b.Property<decimal?>("Total")
                    .HasColumnType("numeric");

                b.HasKey("Id");

                b.HasIndex("CurrencyId");

                b.HasIndex("ModuleId");

                b.ToTable("Movement");
            });

        modelBuilder.Entity("Finance.Api.Models.CurrencyConversion", b =>
            {
                b.HasOne("Finance.Api.Models.Currency", "Currency")
                    .WithMany()
                    .HasForeignKey("CurrencyId");

                b.HasOne("Finance.Api.Models.Movement", "Movement")
                    .WithMany()
                    .HasForeignKey("MovementId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Currency");

                b.Navigation("Movement");
            });

        modelBuilder.Entity("Finance.Api.Models.Module", b =>
            {
                b.HasOne("Finance.Api.Models.Currency", "Currency")
                    .WithMany()
                    .HasForeignKey("CurrencyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Currency");
            });

        modelBuilder.Entity("Finance.Api.Models.Movement", b =>
            {
                b.HasOne("Finance.Api.Models.Currency", "Currency")
                    .WithMany()
                    .HasForeignKey("CurrencyId");

                b.HasOne("Finance.Api.Models.Module", "Module")
                    .WithMany("Movements")
                    .HasForeignKey("ModuleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Currency");

                b.Navigation("Module");
            });

        modelBuilder.Entity("Finance.Api.Models.Module", b =>
            {
                b.Navigation("Movements");
            });
#pragma warning restore 612, 618
    }
}
