// <auto-generated />
using System;
using Finance.Domain;
using Finance.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Finance.Domain.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20240213081502_CurrencyExchangeRates")]
    partial class CurrencyExchangeRates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("Finance.Domain.Models.AppModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("TypeId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("TypeId");

                    b.ToTable("AppModule");
                });

            modelBuilder.Entity("Finance.Domain.Models.AppModuleType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<short>("Id"));

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("AppModuleType");
                });

            modelBuilder.Entity("Finance.Domain.Models.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bank");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("CreditCard");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCardMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AmountDollars")
                        .HasColumnType("numeric");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreditCardId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<int>("PaymentNumber")
                        .HasColumnType("integer");

                    b.Property<int>("PlanSize")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlanStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId");

                    b.ToTable("CreditCardMovement");
                });

            modelBuilder.Entity("Finance.Domain.Models.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("Finance.Domain.Models.CurrencyConversion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MovementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("MovementId");

                    b.ToTable("CurrencyConversion");
                });

            modelBuilder.Entity("Finance.Domain.Models.CurrencyExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseCurrencyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BuyRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuoteCurrencyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SellRate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuoteCurrencyId");

                    b.HasIndex("BaseCurrencyId", "QuoteCurrencyId", "TimeStamp")
                        .IsUnique();

                    b.ToTable("CurrencyExchangeRate");
                });

            modelBuilder.Entity("Finance.Domain.Models.Debit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OriginId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OriginId");

                    b.ToTable("Debit");
                });

            modelBuilder.Entity("Finance.Domain.Models.DebitOrigin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppModuleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppModuleId");

                    b.HasIndex("Name", "AppModuleId")
                        .IsUnique();

                    b.ToTable("DebitOrigin");
                });

            modelBuilder.Entity("Finance.Domain.Models.IOLInvestment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Alarms")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<long>("Assets")
                        .HasColumnType("bigint");

                    b.Property<decimal>("AverageBuyPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AverageReturn")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AverageReturnPercent")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DailyVariation")
                        .HasColumnType("numeric");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LastPrice")
                        .HasColumnType("numeric");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valued")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("IOLInvestment");
                });

            modelBuilder.Entity("Finance.Domain.Models.IOLInvestmentAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("IOLInvestmentAsset");
                });

            modelBuilder.Entity("Finance.Domain.Models.IOLInvestmentAssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("IOLInvestmentAssetType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deactivated = false,
                            Name = "Cedear"
                        },
                        new
                        {
                            Id = 2,
                            Deactivated = false,
                            Name = "TituloPublico"
                        },
                        new
                        {
                            Id = 3,
                            Deactivated = false,
                            Name = "FCI"
                        },
                        new
                        {
                            Id = 4,
                            Deactivated = false,
                            Name = "ObligacionNegociable"
                        });
                });

            modelBuilder.Entity("Finance.Domain.Models.Movement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("AppModuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid");

                    b.Property<string>("Concept1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Concept2")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AppModuleId");

                    b.HasIndex("BankId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Movement");
                });

            modelBuilder.Entity("Finance.Domain.Models.AppModule", b =>
                {
                    b.HasOne("Finance.Domain.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.AppModuleType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCard", b =>
                {
                    b.HasOne("Finance.Domain.Models.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCardMovement", b =>
                {
                    b.HasOne("Finance.Domain.Models.CreditCard", "CreditCard")
                        .WithMany("Movements")
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCard");
                });

            modelBuilder.Entity("Finance.Domain.Models.CurrencyConversion", b =>
                {
                    b.HasOne("Finance.Domain.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.HasOne("Finance.Domain.Models.Movement", "Movement")
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Movement");
                });

            modelBuilder.Entity("Finance.Domain.Models.CurrencyExchangeRate", b =>
                {
                    b.HasOne("Finance.Domain.Models.Currency", "BaseCurrency")
                        .WithMany()
                        .HasForeignKey("BaseCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.Currency", "QuoteCurrency")
                        .WithMany()
                        .HasForeignKey("QuoteCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseCurrency");

                    b.Navigation("QuoteCurrency");
                });

            modelBuilder.Entity("Finance.Domain.Models.Debit", b =>
                {
                    b.HasOne("Finance.Domain.Models.DebitOrigin", "Origin")
                        .WithMany("Debits")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("Finance.Domain.Models.DebitOrigin", b =>
                {
                    b.HasOne("Finance.Domain.Models.AppModule", "AppModule")
                        .WithMany()
                        .HasForeignKey("AppModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppModule");
                });

            modelBuilder.Entity("Finance.Domain.Models.IOLInvestment", b =>
                {
                    b.HasOne("Finance.Domain.Models.IOLInvestmentAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Finance.Domain.Models.IOLInvestmentAsset", b =>
                {
                    b.HasOne("Finance.Domain.Models.IOLInvestmentAssetType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Finance.Domain.Models.Movement", b =>
                {
                    b.HasOne("Finance.Domain.Models.AppModule", "AppModule")
                        .WithMany("Movements")
                        .HasForeignKey("AppModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.Navigation("AppModule");

                    b.Navigation("Bank");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Finance.Domain.Models.AppModule", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCard", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("Finance.Domain.Models.DebitOrigin", b =>
                {
                    b.Navigation("Debits");
                });
#pragma warning restore 612, 618
        }
    }
}
