// <auto-generated />
using System;
using Finance.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Finance.Domain.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20251116112051_SimplifiedPermissionsModel")]
    partial class SimplifiedPermissionsModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("Finance.Domain.Models.AppModules.AppModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("TypeId")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("TypeId");

                    b.ToTable("AppModule");
                });

            modelBuilder.Entity("Finance.Domain.Models.AppModules.AppModuleType", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AppModuleType");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deactivated = false,
                            Name = "Funds",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = (short)2,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deactivated = false,
                            Name = "Debits",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = (short)3,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deactivated = false,
                            Name = "Investments",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.CreditCardPermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("PermissionLevels")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "UserId")
                        .IsUnique();

                    b.ToTable("CreditCardPermissions");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.CurrencyExchangeRatePermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("PermissionLevels")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "UserId")
                        .IsUnique();

                    b.ToTable("CurrencyExchangeRatePermissions");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.DebitOriginPermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("PermissionLevels")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "UserId")
                        .IsUnique();

                    b.ToTable("DebitOriginPermissions");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.DebitPermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("PermissionLevels")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "UserId")
                        .IsUnique();

                    b.ToTable("DebitPermissions");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.FundPermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("PermissionLevels")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "UserId")
                        .IsUnique();

                    b.ToTable("FundPermissions");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.IOLInvestmentAssetPermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("PermissionLevels")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "UserId")
                        .IsUnique();

                    b.ToTable("IOLInvestmentAssetPermissions");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.IOLInvestmentPermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("PermissionLevels")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "UserId")
                        .IsUnique();

                    b.ToTable("IOLInvestmentPermissions");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.IncomePermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("PermissionLevels")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "UserId")
                        .IsUnique();

                    b.ToTable("IncomePermissions");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.MovementPermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("PermissionLevels")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "UserId")
                        .IsUnique();

                    b.ToTable("MovementPermissions");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.Role", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deactivated = false,
                            Name = "Admin",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = (short)2,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deactivated = false,
                            Name = "Owner",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Finance.Domain.Models.Banks.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Bank");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCards.CreditCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreditCardIssuerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentStatementId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("UnappliedCredit")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardIssuerId");

                    b.HasIndex("CurrentStatementId");

                    b.HasIndex("BankId", "Name");

                    b.ToTable("CreditCard");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCards.CreditCardIssuer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CreditCardIssuer");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCards.CreditCardPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<Guid>("StatementId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StatementId", "Timestamp");

                    b.ToTable("CreditCardPayment");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCards.CreditCardStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClosureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreditCardId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ExpiringDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MinimumDue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId", "ClosureDate");

                    b.ToTable("CreditCardStatement");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCards.CreditCardStatementAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreditCardStatementId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardStatementId", "CreatedAt");

                    b.ToTable("CreditCardStatementAdjustment");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCards.CreditCardStatementTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CreditCardStatementId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreditCardTransactionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardTransactionId");

                    b.HasIndex("CreditCardStatementId", "PostedDate");

                    b.ToTable("CreditCardStatementTransaction");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCards.CreditCardTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("CreditCardId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("StatementTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransactionType")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatementTransactionId");

                    b.HasIndex("CreditCardId", "Timestamp");

                    b.ToTable("CreditCardTransaction");
                });

            modelBuilder.Entity("Finance.Domain.Models.Currencies.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.HasIndex("Name", "ShortName")
                        .IsUnique();

                    b.ToTable("Currency");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d189135-7040-45a1-b713-b1aa6cad1720"),
                            Deactivated = false,
                            Name = "Peso",
                            ShortName = "ARS"
                        },
                        new
                        {
                            Id = new Guid("efbf50bc-34d4-43e9-96f9-9f6213ea11b5"),
                            Deactivated = false,
                            Name = "Dollar",
                            ShortName = "USD"
                        });
                });

            modelBuilder.Entity("Finance.Domain.Models.Currencies.CurrencyConversion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MovementId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("MovementId");

                    b.ToTable("CurrencyConversion");
                });

            modelBuilder.Entity("Finance.Domain.Models.Currencies.CurrencyExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseCurrencyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BuyRate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuoteCurrencyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SellRate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuoteCurrencyId");

                    b.HasIndex("BaseCurrencyId", "QuoteCurrencyId", "TimeStamp")
                        .IsUnique();

                    b.ToTable("CurrencyExchangeRate");
                });

            modelBuilder.Entity("Finance.Domain.Models.Currencies.CurrencySymbol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("Symbol", "CurrencyId")
                        .IsUnique();

                    b.ToTable("CurrencySymbols");

                    b.HasData(
                        new
                        {
                            Id = new Guid("31d219c8-90a2-437b-8e52-f5fbf3bbd24f"),
                            CurrencyId = new Guid("6d189135-7040-45a1-b713-b1aa6cad1720"),
                            Deactivated = false,
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("0a3d9502-aeec-4c35-92c1-9dc36c40612f"),
                            CurrencyId = new Guid("efbf50bc-34d4-43e9-96f9-9f6213ea11b5"),
                            Deactivated = false,
                            Symbol = "USD"
                        },
                        new
                        {
                            Id = new Guid("9b0ddd93-b13c-4443-ba97-0996672cbc1a"),
                            CurrencyId = new Guid("efbf50bc-34d4-43e9-96f9-9f6213ea11b5"),
                            Deactivated = false,
                            Symbol = "U$D"
                        },
                        new
                        {
                            Id = new Guid("9db01d76-76b0-438a-a6f3-38c4dda33ff4"),
                            CurrencyId = new Guid("efbf50bc-34d4-43e9-96f9-9f6213ea11b5"),
                            Deactivated = false,
                            Symbol = "US$"
                        });
                });

            modelBuilder.Entity("Finance.Domain.Models.Debits.Debit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<short>("Frequency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<Guid>("OriginId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Frequency");

                    b.HasIndex("OriginId");

                    b.ToTable("Debit");
                });

            modelBuilder.Entity("Finance.Domain.Models.Debits.DebitOrigin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppModuleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppModuleId");

                    b.HasIndex("Name", "AppModuleId")
                        .IsUnique();

                    b.ToTable("DebitOrigin");
                });

            modelBuilder.Entity("Finance.Domain.Models.Frequencies.Frequency", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Frequency");

                    b.HasData(
                        new
                        {
                            Id = (short)0,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deactivated = false,
                            Name = "Monthly",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = (short)1,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deactivated = false,
                            Name = "Annual",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Finance.Domain.Models.Frequencies.PermissionLevel", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PermissionLevel");

                    b.HasData(
                        new
                        {
                            Id = (short)0,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deactivated = false,
                            Name = "None",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = (short)1,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deactivated = false,
                            Name = "Read",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = (short)2,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deactivated = false,
                            Name = "Write",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = (short)3,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deactivated = false,
                            Name = "Owner",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Finance.Domain.Models.Funds.Fund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DailyUse")
                        .HasColumnType("boolean");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Fund");
                });

            modelBuilder.Entity("Finance.Domain.Models.IOLInvestments.IOLInvestment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Alarms")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<long>("Assets")
                        .HasColumnType("bigint");

                    b.Property<decimal>("AverageBuyPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AverageReturn")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AverageReturnPercent")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DailyVariation")
                        .HasColumnType("numeric");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LastPrice")
                        .HasColumnType("numeric");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valued")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("IOLInvestment");
                });

            modelBuilder.Entity("Finance.Domain.Models.IOLInvestments.IOLInvestmentAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("TypeId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("TypeId");

                    b.ToTable("IOLInvestmentAsset");
                });

            modelBuilder.Entity("Finance.Domain.Models.IOLInvestments.IOLInvestmentAssetType", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("IOLInvestmentAssetType");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deactivated = false,
                            Name = "Cedear",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = (short)2,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deactivated = false,
                            Name = "TituloPublico",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = (short)3,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deactivated = false,
                            Name = "FCI",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = (short)4,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deactivated = false,
                            Name = "ObligacionNegociable",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Finance.Domain.Models.Identities.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<short>("Provider")
                        .HasColumnType("smallint");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Identity");
                });

            modelBuilder.Entity("Finance.Domain.Models.Identities.IdentityProvider", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("IdentityProvider");

                    b.HasData(
                        new
                        {
                            Id = (short)0,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deactivated = false,
                            Name = "None",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = (short)1,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deactivated = false,
                            Name = "Auth",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Finance.Domain.Models.Incomes.Income", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Income");
                });

            modelBuilder.Entity("Finance.Domain.Models.Movements.Movement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("AppModuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid");

                    b.Property<string>("Concept1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Concept2")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppModuleId");

                    b.HasIndex("BankId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Movement");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Finance.Domain.Models.AppModules.AppModule", b =>
                {
                    b.HasOne("Finance.Domain.Models.Currencies.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.AppModules.AppModuleType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.CreditCardPermissions", b =>
                {
                    b.HasOne("Finance.Domain.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.CreditCards.CreditCard", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.CurrencyExchangeRatePermissions", b =>
                {
                    b.HasOne("Finance.Domain.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.Currencies.CurrencyExchangeRate", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.DebitOriginPermissions", b =>
                {
                    b.HasOne("Finance.Domain.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.Debits.DebitOrigin", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.DebitPermissions", b =>
                {
                    b.HasOne("Finance.Domain.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.Debits.Debit", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.FundPermissions", b =>
                {
                    b.HasOne("Finance.Domain.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.Funds.Fund", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.IOLInvestmentAssetPermissions", b =>
                {
                    b.HasOne("Finance.Domain.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.IOLInvestments.IOLInvestmentAsset", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.IOLInvestmentPermissions", b =>
                {
                    b.HasOne("Finance.Domain.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.IOLInvestments.IOLInvestment", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.IncomePermissions", b =>
                {
                    b.HasOne("Finance.Domain.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.Incomes.Income", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.MovementPermissions", b =>
                {
                    b.HasOne("Finance.Domain.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.Movements.Movement", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCards.CreditCard", b =>
                {
                    b.HasOne("Finance.Domain.Models.Banks.Bank", "Bank")
                        .WithMany("CreditCards")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.CreditCards.CreditCardIssuer", "CreditCardIssuer")
                        .WithMany("CreditCards")
                        .HasForeignKey("CreditCardIssuerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Finance.Domain.Models.CreditCards.CreditCardStatement", "CurrentStatement")
                        .WithMany()
                        .HasForeignKey("CurrentStatementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bank");

                    b.Navigation("CreditCardIssuer");

                    b.Navigation("CurrentStatement");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCards.CreditCardPayment", b =>
                {
                    b.HasOne("Finance.Domain.Models.CreditCards.CreditCardStatement", "Statement")
                        .WithMany()
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCards.CreditCardStatement", b =>
                {
                    b.HasOne("Finance.Domain.Models.CreditCards.CreditCard", "CreditCard")
                        .WithMany("Statements")
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreditCard");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCards.CreditCardStatementAdjustment", b =>
                {
                    b.HasOne("Finance.Domain.Models.CreditCards.CreditCardStatement", "CreditCardStatement")
                        .WithMany()
                        .HasForeignKey("CreditCardStatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCardStatement");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCards.CreditCardStatementTransaction", b =>
                {
                    b.HasOne("Finance.Domain.Models.CreditCards.CreditCardStatement", "CreditCardStatement")
                        .WithMany()
                        .HasForeignKey("CreditCardStatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.CreditCards.CreditCardTransaction", "CreditCardTransaction")
                        .WithMany()
                        .HasForeignKey("CreditCardTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreditCardStatement");

                    b.Navigation("CreditCardTransaction");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCards.CreditCardTransaction", b =>
                {
                    b.HasOne("Finance.Domain.Models.CreditCards.CreditCard", "CreditCard")
                        .WithMany("Transactions")
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.CreditCards.CreditCardStatementTransaction", "StatementTransaction")
                        .WithMany()
                        .HasForeignKey("StatementTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreditCard");

                    b.Navigation("StatementTransaction");
                });

            modelBuilder.Entity("Finance.Domain.Models.Currencies.CurrencyConversion", b =>
                {
                    b.HasOne("Finance.Domain.Models.Currencies.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.HasOne("Finance.Domain.Models.Movements.Movement", "Movement")
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Movement");
                });

            modelBuilder.Entity("Finance.Domain.Models.Currencies.CurrencyExchangeRate", b =>
                {
                    b.HasOne("Finance.Domain.Models.Currencies.Currency", "BaseCurrency")
                        .WithMany("BaseExchangeRates")
                        .HasForeignKey("BaseCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.Currencies.Currency", "QuoteCurrency")
                        .WithMany("QuoteExchangeRates")
                        .HasForeignKey("QuoteCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseCurrency");

                    b.Navigation("QuoteCurrency");
                });

            modelBuilder.Entity("Finance.Domain.Models.Currencies.CurrencySymbol", b =>
                {
                    b.HasOne("Finance.Domain.Models.Currencies.Currency", "Currency")
                        .WithMany("Symbols")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Finance.Domain.Models.Debits.Debit", b =>
                {
                    b.HasOne("Finance.Domain.Models.Frequencies.Frequency", null)
                        .WithMany()
                        .HasForeignKey("Frequency")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.Debits.DebitOrigin", "Origin")
                        .WithMany("Debits")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("Finance.Domain.Models.Debits.DebitOrigin", b =>
                {
                    b.HasOne("Finance.Domain.Models.AppModules.AppModule", "AppModule")
                        .WithMany()
                        .HasForeignKey("AppModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppModule");
                });

            modelBuilder.Entity("Finance.Domain.Models.Funds.Fund", b =>
                {
                    b.HasOne("Finance.Domain.Models.Banks.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.Currencies.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Finance.Domain.Models.IOLInvestments.IOLInvestment", b =>
                {
                    b.HasOne("Finance.Domain.Models.IOLInvestments.IOLInvestmentAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Finance.Domain.Models.IOLInvestments.IOLInvestmentAsset", b =>
                {
                    b.HasOne("Finance.Domain.Models.Currencies.Currency", "Currency")
                        .WithMany("IOLInvestmentAssets")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.IOLInvestments.IOLInvestmentAssetType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Finance.Domain.Models.Identities.Identity", b =>
                {
                    b.HasOne("Finance.Domain.Models.Auth.User", "User")
                        .WithMany("Identities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance.Domain.Models.Incomes.Income", b =>
                {
                    b.HasOne("Finance.Domain.Models.Banks.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.Currencies.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Finance.Domain.Models.Movements.Movement", b =>
                {
                    b.HasOne("Finance.Domain.Models.AppModules.AppModule", "AppModule")
                        .WithMany("Movements")
                        .HasForeignKey("AppModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.Banks.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.Currencies.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.Navigation("AppModule");

                    b.Navigation("Bank");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("Finance.Domain.Models.Auth.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Domain.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Finance.Domain.Models.AppModules.AppModule", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("Finance.Domain.Models.Auth.User", b =>
                {
                    b.Navigation("Identities");
                });

            modelBuilder.Entity("Finance.Domain.Models.Banks.Bank", b =>
                {
                    b.Navigation("CreditCards");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCards.CreditCard", b =>
                {
                    b.Navigation("Statements");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Finance.Domain.Models.CreditCards.CreditCardIssuer", b =>
                {
                    b.Navigation("CreditCards");
                });

            modelBuilder.Entity("Finance.Domain.Models.Currencies.Currency", b =>
                {
                    b.Navigation("BaseExchangeRates");

                    b.Navigation("IOLInvestmentAssets");

                    b.Navigation("QuoteExchangeRates");

                    b.Navigation("Symbols");
                });

            modelBuilder.Entity("Finance.Domain.Models.Debits.DebitOrigin", b =>
                {
                    b.Navigation("Debits");
                });
#pragma warning restore 612, 618
        }
    }
}
