services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=finance
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ../../../FinanceBackEnd
      dockerfile: Finance.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./dataprotection:/root/.aspnet/DataProtection-Keys
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/swagger/index.html"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  redis-data:
  postgres-data:
networks:
  default:
    name: shared_network
    driver: bridge
