export const VARIANTS = {
    PRIMARY: 'primary',
    SECONDARY: 'secondary',
    SUCCESS: 'success',
    DANGER: 'danger',
    WARNING: 'warning',
    INFO: 'info',
    LIGHT: 'light',
    DARK: 'dark'
}

export const OUTLINE_VARIANTS = {
    PRIMARY: `outline-${VARIANTS.PRIMARY}`,
    SECONDARY: `outline-${VARIANTS.SECONDARY}`,
    SUCCESS: `outline-${VARIANTS.SUCCESS}`,
    DANGER: `outline-${VARIANTS.DANGER}`,
    WARNING: `outline-${VARIANTS.WARNING}`,
    INFO: `outline-${VARIANTS.INFO}`,
    LIGHT: `outline-${VARIANTS.LIGHT}`,
    DARK: `outline-${VARIANTS.DARK}`
}

export const BUTTON_VARIANTS = {
    PRIMARY: `btn-${VARIANTS.PRIMARY}`,
    SECONDARY: `btn-${VARIANTS.SECONDARY}`,
    SUCCESS: `btn-${VARIANTS.SUCCESS}`,
    DANGER: `btn-${VARIANTS.DANGER}`,
    WARNING: `btn-${VARIANTS.WARNING}`,
    INFO: `btn-${VARIANTS.INFO}`,
    LIGHT: `btn-${VARIANTS.LIGHT}`,
    DARK: `btn-${VARIANTS.DARK}`
}

export const BUTTON_OUTLINE_VARIANTS = {
    PRIMARY: `btn-${OUTLINE_VARIANTS.PRIMARY}`,
    SECONDARY: `btn-${OUTLINE_VARIANTS.SECONDARY}`,
    SUCCESS: `btn-${OUTLINE_VARIANTS.SUCCESS}`,
    DANGER: `btn-${OUTLINE_VARIANTS.DANGER}`,
    WARNING: `btn-${OUTLINE_VARIANTS.WARNING}`,
    INFO: `btn-${OUTLINE_VARIANTS.INFO}`,
    LIGHT: `btn-${OUTLINE_VARIANTS.LIGHT}`,
    DARK: `btn-${OUTLINE_VARIANTS.DARK}`
}

export type COLOR_VARIANTS = typeof VARIANTS.PRIMARY 
| typeof VARIANTS.SECONDARY
| typeof VARIANTS.SUCCESS
| typeof VARIANTS.DANGER
| typeof VARIANTS.WARNING
| typeof VARIANTS.INFO
| typeof VARIANTS.LIGHT
| typeof VARIANTS.DARK;


export type BUTTON_COLOR_VARIANTS = typeof BUTTON_VARIANTS.PRIMARY 
| typeof BUTTON_VARIANTS.SECONDARY
| typeof BUTTON_VARIANTS.SUCCESS
| typeof BUTTON_VARIANTS.DANGER
| typeof BUTTON_VARIANTS.WARNING
| typeof BUTTON_VARIANTS.INFO
| typeof BUTTON_VARIANTS.LIGHT
| typeof BUTTON_VARIANTS.DARK;

export type BUTTON_OUTLINE_COLOR_VARIANTS = typeof BUTTON_OUTLINE_VARIANTS.PRIMARY 
| typeof BUTTON_OUTLINE_VARIANTS.SECONDARY
| typeof BUTTON_OUTLINE_VARIANTS.SUCCESS
| typeof BUTTON_OUTLINE_VARIANTS.DANGER
| typeof BUTTON_OUTLINE_VARIANTS.WARNING
| typeof BUTTON_OUTLINE_VARIANTS.INFO
| typeof BUTTON_OUTLINE_VARIANTS.LIGHT
| typeof BUTTON_OUTLINE_VARIANTS.DARK;