export const VARIANT = {
    PRIMARY: 'primary',
    SECONDARY: 'secondary',
    SUCCESS: 'success',
    DANGER: 'danger',
    WARNING: 'warning',
    INFO: 'info',
    LIGHT: 'light',
    DARK: 'dark'
}

export const OUTLINE_VARIANT = {
    PRIMARY: `outline-${VARIANT.PRIMARY}`,
    SECONDARY: `outline-${VARIANT.SECONDARY}`,
    SUCCESS: `outline-${VARIANT.SUCCESS}`,
    DANGER: `outline-${VARIANT.DANGER}`,
    WARNING: `outline-${VARIANT.WARNING}`,
    INFO: `outline-${VARIANT.INFO}`,
    LIGHT: `outline-${VARIANT.LIGHT}`,
    DARK: `outline-${VARIANT.DARK}`
}

export const BUTTON_VARIANT = {
    PRIMARY: `btn-${VARIANT.PRIMARY}`,
    SECONDARY: `btn-${VARIANT.SECONDARY}`,
    SUCCESS: `btn-${VARIANT.SUCCESS}`,
    DANGER: `btn-${VARIANT.DANGER}`,
    WARNING: `btn-${VARIANT.WARNING}`,
    INFO: `btn-${VARIANT.INFO}`,
    LIGHT: `btn-${VARIANT.LIGHT}`,
    DARK: `btn-${VARIANT.DARK}`
}

export const BUTTON_OUTLINE_VARIANT = {
    PRIMARY: `btn-${OUTLINE_VARIANT.PRIMARY}`,
    SECONDARY: `btn-${OUTLINE_VARIANT.SECONDARY}`,
    SUCCESS: `btn-${OUTLINE_VARIANT.SUCCESS}`,
    DANGER: `btn-${OUTLINE_VARIANT.DANGER}`,
    WARNING: `btn-${OUTLINE_VARIANT.WARNING}`,
    INFO: `btn-${OUTLINE_VARIANT.INFO}`,
    LIGHT: `btn-${OUTLINE_VARIANT.LIGHT}`,
    DARK: `btn-${OUTLINE_VARIANT.DARK}`
}

export type COLOR_VARIANT = typeof VARIANT.PRIMARY 
| typeof VARIANT.SECONDARY
| typeof VARIANT.SUCCESS
| typeof VARIANT.DANGER
| typeof VARIANT.WARNING
| typeof VARIANT.INFO
| typeof VARIANT.LIGHT
| typeof VARIANT.DARK;

export type BUTTON_COLOR_VARIANT = typeof BUTTON_VARIANT.PRIMARY 
| typeof BUTTON_VARIANT.SECONDARY
| typeof BUTTON_VARIANT.SUCCESS
| typeof BUTTON_VARIANT.DANGER
| typeof BUTTON_VARIANT.WARNING
| typeof BUTTON_VARIANT.INFO
| typeof BUTTON_VARIANT.LIGHT
| typeof BUTTON_VARIANT.DARK;

export type BUTTON_OUTLINE_COLOR_VARIANT = typeof BUTTON_OUTLINE_VARIANT.PRIMARY 
| typeof BUTTON_OUTLINE_VARIANT.SECONDARY
| typeof BUTTON_OUTLINE_VARIANT.SUCCESS
| typeof BUTTON_OUTLINE_VARIANT.DANGER
| typeof BUTTON_OUTLINE_VARIANT.WARNING
| typeof BUTTON_OUTLINE_VARIANT.INFO
| typeof BUTTON_OUTLINE_VARIANT.LIGHT
| typeof BUTTON_OUTLINE_VARIANT.DARK;